[AOD-14985] Add support for Microsoft OAuth2 ID tokens
AODocs/endpoints-authenticators pull request #21
Opened 2024-12-16 09:41 UTC by gmazak

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/AODocs/endpoints-authenticators/21)

2024-12-17 10:05 UTC, adambiroaliz approved these changes

2024-12-17 21:22 UTC, RaHery reviewed
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/AODocs/endpoints-authenticators/21)* status: all files reviewed, 2 unresolved discussions (waiting on @gmazak)

___
*[`src/main/java/com/aodocs/endpoints/auth/authorizers/clientid/ClientIdsAuthorizer.java` line 41 at r1](https://reviewable.io/reviews/AODocs/endpoints-authenticators/21#-OELU4Ct5I1g2rtg9uby:-OELU4Ct5I1g2rtg9ubz:bkus1o7) ([raw file](https://github.com/AODocs/endpoints-authenticators/blob/eb0d7e0607b7672aad7c5ff5339c488f3b445758/src/main/java/com/aodocs/endpoints/auth/authorizers/clientid/ClientIdsAuthorizer.java#L41)):*
> ```Java
> /**
>  * This authenticator allows any token issued by a client id in the provided list.
>  * In case of a Microsoft Oauth2 ID token, the audience (Entra ID application ID that the token was issued for) is checked instead of the client id.
> ```

Hum ...
Why don't we create a specific authorizer to authorize "aud" claim instead of mixing it here? We can parameterize the authorizer so that it applies only on "aud" claims of microsoft token. 
___
*[`src/main/java/com/aodocs/endpoints/auth/AuthInfo.java` line 153 at r1](https://reviewable.io/reviews/AODocs/endpoints-authenticators/21#-OELTGIE5HdG1CjGMATM:-OELTGIFDpTISM9cX_0M:b-z4yhev) ([raw file](https://github.com/AODocs/endpoints-authenticators/blob/eb0d7e0607b7672aad7c5ff5339c488f3b445758/src/main/java/com/aodocs/endpoints/auth/AuthInfo.java#L153)):*
> ```Java
>         this.verifiedEmail = true;
>         this.hd = null;
>         this.clientId = null;
> ```

Isnt't the `aud` claim supposed to be the "equivalent" of clientId?


<!-- Sent from Reviewable.io -->

2024-12-18 08:45 UTC, gmazak reviewed
> *[Reviewable](https://reviewable.io/reviews/AODocs/endpoints-authenticators/21)* status: all files reviewed, 2 unresolved discussions (waiting on @RaHery)

___
*[`src/main/java/com/aodocs/endpoints/auth/AuthInfo.java` line 153 at r1](https://reviewable.io/reviews/AODocs/endpoints-authenticators/21#-OELTGIE5HdG1CjGMATM:-OENu9zu3YXnt5TCfG-q:b-l1j3ba) ([raw file](https://github.com/AODocs/endpoints-authenticators/blob/eb0d7e0607b7672aad7c5ff5339c488f3b445758/src/main/java/com/aodocs/endpoints/auth/AuthInfo.java#L153)):*
<details><summary><i>Previously, RaHery (Hermann RANGAMANA) wrote…</i></summary><blockquote>

Isnt't the `aud` claim supposed to be the "equivalent" of clientId?
</blockquote></details>

That's right.

I wanted to make it clear that we don't have a `clientId` here.
The corresponding authorization classes need to handle the audience for these tokens as they were clientIds.
___
*[`src/main/java/com/aodocs/endpoints/auth/authorizers/clientid/ClientIdsAuthorizer.java` line 41 at r1](https://reviewable.io/reviews/AODocs/endpoints-authenticators/21#-OELU4Ct5I1g2rtg9uby:-OENuv7x2jkjvUTSCNni:bi3pg21) ([raw file](https://github.com/AODocs/endpoints-authenticators/blob/eb0d7e0607b7672aad7c5ff5339c488f3b445758/src/main/java/com/aodocs/endpoints/auth/authorizers/clientid/ClientIdsAuthorizer.java#L41)):*
<details><summary><i>Previously, RaHery (Hermann RANGAMANA) wrote…</i></summary><blockquote>

Hum ...
Why don't we create a specific authorizer to authorize "aud" claim instead of mixing it here? We can parameterize the authorizer so that it applies only on "aud" claims of microsoft token.
</blockquote></details>

The general idea was to reuse the same  infrastructure to allowlist a Microsoft Entra ID application as we have for GCP clientIds.

If i understand your suggestion well, you're suggesting to create a dedicated authorizer class to handle MS OAuth2 tokens.
We would need to basically copy-paste the following content in `authenticator.yaml` in AODocs Core to reuse the various allowlists:

```
  - clientIds:
      classpathResource: "${common-client-ids}"
      failOnMissing: false
  - clientIds:
      classpathResource: "${customer-client-ids}"
      failOnMissing: false
  - clientIds:
      datastoreEntity: "ClientId"
      namespace: "-GLOBAL-"
      ttlInSeconds: 300
      limit: 500
```

Is my understanding correct?


<!-- Sent from Reviewable.io -->

2024-12-19 07:31 UTC, gmazak reviewed
> *[Reviewable](https://reviewable.io/reviews/AODocs/endpoints-authenticators/21)* status: 0 of 20 files reviewed, 2 unresolved discussions (waiting on @RaHery)

___
*[`src/main/java/com/aodocs/endpoints/auth/AuthInfo.java` line 153 at r1](https://reviewable.io/reviews/AODocs/endpoints-authenticators/21#-OELTGIE5HdG1CjGMATM:-OESollo2VNBjy9VMl6A:bb6un1j) ([raw file](https://github.com/AODocs/endpoints-authenticators/blob/eb0d7e0607b7672aad7c5ff5339c488f3b445758/src/main/java/com/aodocs/endpoints/auth/AuthInfo.java#L153)):*
<details><summary><i>Previously, gmazak wrote…</i></summary><blockquote>

That's right.

I wanted to make it clear that we don't have a `clientId` here.
The corresponding authorization classes need to handle the audience for these tokens as they were clientIds.
</blockquote></details>

Done
___
*[`src/main/java/com/aodocs/endpoints/auth/authorizers/clientid/ClientIdsAuthorizer.java` line 41 at r1](https://reviewable.io/reviews/AODocs/endpoints-authenticators/21#-OELU4Ct5I1g2rtg9uby:-OESot2PAuLeVrrg2VhE:bylr63h) ([raw file](https://github.com/AODocs/endpoints-authenticators/blob/eb0d7e0607b7672aad7c5ff5339c488f3b445758/src/main/java/com/aodocs/endpoints/auth/authorizers/clientid/ClientIdsAuthorizer.java#L41)):*
<details><summary><i>Previously, gmazak wrote…</i></summary><blockquote>

The general idea was to reuse the same  infrastructure to allowlist a Microsoft Entra ID application as we have for GCP clientIds.

If i understand your suggestion well, you're suggesting to create a dedicated authorizer class to handle MS OAuth2 tokens.
We would need to basically copy-paste the following content in `authenticator.yaml` in AODocs Core to reuse the various allowlists:

```
  - clientIds:
      classpathResource: "${common-client-ids}"
      failOnMissing: false
  - clientIds:
      classpathResource: "${customer-client-ids}"
      failOnMissing: false
  - clientIds:
      datastoreEntity: "ClientId"
      namespace: "-GLOBAL-"
      ttlInSeconds: 300
      limit: 500
```

Is my understanding correct?
</blockquote></details>

Discussed IRL, the requested changes are done


<!-- Sent from Reviewable.io -->

2024-12-19 08:12 UTC, RaHery requested changes
> Reviewed 20 of 20 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/AODocs/endpoints-authenticators/21)* status: all files reviewed, 2 unresolved discussions (waiting on @gmazak)

___
*[a discussion](https://reviewable.io/reviews/AODocs/endpoints-authenticators/21#-OESvHwT0tsnN1cK8uQ-:-OESvHwT0tsnN1cK8uQ0:bvdfjcy) (no related file):*
On package organization, i would put the new package `microsoft` as subpackage of  `auth.authenticator` because it contains mainly support classes for the implementation of `MicrosoftOAuth2Authenticator` .

Optionally, i would also move the `MicrosoftOAuth2Authenticator` into the same package: the advantage is that all of those support classes can be put in same package with lower visibility - package private for example (we do not use jigsaw's modules yet ...). 
___
*[`src/main/java/com/aodocs/endpoints/auth/authorizers/dsl/DslAuthorizerConfig.java` line 91 at r2](https://reviewable.io/reviews/AODocs/endpoints-authenticators/21#-OESsvFS-TP5o2QXhHfG:-OESsvFTAyR0RhD27Vhy:b-b98yu7) ([raw file](https://github.com/AODocs/endpoints-authenticators/blob/ce4e742f20dc082cf4ecc324d2391e7b7ccdaf68/src/main/java/com/aodocs/endpoints/auth/authorizers/dsl/DslAuthorizerConfig.java#L91)):*
> ```Java
>             .put("httpMethod", HttpMethodAuthorizer.class)
>             .put("clientIds", ClientIdsAuthorizer.class)
>             .put("entra-id-appids", EntraIdApplicationAuthorizer.class)
> ```

Well, we've been using camelcase so far :) `entraIdsAppids` maybe ?


<!-- Sent from Reviewable.io -->

2024-12-19 08:58 UTC, gmazak reviewed
> *[Reviewable](https://reviewable.io/reviews/AODocs/endpoints-authenticators/21)* status: all files reviewed, 2 unresolved discussions (waiting on @RaHery)

___
*[`src/main/java/com/aodocs/endpoints/auth/authorizers/dsl/DslAuthorizerConfig.java` line 91 at r2](https://reviewable.io/reviews/AODocs/endpoints-authenticators/21#-OESsvFS-TP5o2QXhHfG:-OET7nue0CoibPehN0On:bxopjnk) ([raw file](https://github.com/AODocs/endpoints-authenticators/blob/ce4e742f20dc082cf4ecc324d2391e7b7ccdaf68/src/main/java/com/aodocs/endpoints/auth/authorizers/dsl/DslAuthorizerConfig.java#L91)):*
<details><summary><i>Previously, RaHery (Hermann RANGAMANA) wrote…</i></summary><blockquote>

Well, we've been using camelcase so far :) `entraIdsAppids` maybe ?
</blockquote></details>

OK, i go for the `entraIdAppIds` notation


<!-- Sent from Reviewable.io -->

2024-12-19 09:03 UTC, gmazak reviewed
> *[Reviewable](https://reviewable.io/reviews/AODocs/endpoints-authenticators/21)* status: all files reviewed, 2 unresolved discussions (waiting on @RaHery)

___
*[a discussion](https://reviewable.io/reviews/AODocs/endpoints-authenticators/21#-OESvHwT0tsnN1cK8uQ-:-OET96is1hz6iY2DVCSr:b-896fix) (no related file):*
<details><summary><i>Previously, RaHery (Hermann RANGAMANA) wrote…</i></summary><blockquote>

On package organization, i would put the new package `microsoft` as subpackage of  `auth.authenticator` because it contains mainly support classes for the implementation of `MicrosoftOAuth2Authenticator` .

Optionally, i would also move the `MicrosoftOAuth2Authenticator` into the same package: the advantage is that all of those support classes can be put in same package with lower visibility - package private for example (we do not use jigsaw's modules yet ...).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-19 16:34 UTC, RaHery approved these changes
> Reviewed 16 of 16 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/AODocs/endpoints-authenticators/21)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gmazak)



<!-- Sent from Reviewable.io -->

2025-01-06 07:29 UTC, merged